In [1]:
import numpy as np

# Difference B/W Array and List
### Numpy array is faster tham python list


In [4]:
# Array
x=np.array([1,2,3,4])
print(x)
print(type(x))

[1 2 3 4]
<class 'numpy.ndarray'>


In [5]:
# List
y = [1,2,3,4]
print(y)
print(type(y))


[1, 2, 3, 4]
<class 'list'>


In [6]:
%timeit [j**4 for j in range(1,9)]  #it is used  for single line


2.5 µs ± 46.1 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [8]:
%timeit np.arange(1,9)**4  #it is used  for single line

2 µs ± 27 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)


# Create numpy array and multidimenssion array
### Number of square bracket represent the dimenssion
 [1 2 3 4] 1 dimenssion,
 [[1 2 3 4]] 2 dimenssion,
 [[[1 2 3 4]]] 3 dimenssion

In [10]:
x=[1,2,3,4,5,6]
y= np.array(x)
print(y)
y

[1 2 3 4 5 6]


array([1, 2, 3, 4, 5, 6])

In [15]:
l=[]

for i in range(1,6):
    int_h = int(input("Enter :"))
    l.append(int_h)
    
print(np.array(l))
np.array(l)
print(y.ndim) # varriable.ndim it will return the dimmension of array

Enter :11
Enter :12
Enter :3
Enter :14
Enter :15
[11 12  3 14 15]
1


# 2Dimmension

In [19]:
n = np.array([[1,2,3,4],[1,2,3,4]]) # no of data always equal in both brackets
print(n)
print(n.ndim)

[[1 2 3 4]
 [1 2 3 4]]
2


# 3 Dimenssion

In [21]:
n = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]]) # no of data always equal in both brackets
print(n)
print(n.ndim)

[[[1 2 3 4]
  [1 2 3 4]
  [1 2 3 4]]]
3


# Multidimenssion Array

In [23]:
n  = np.array([1,2,3,4,5], ndmin = 10) # n.dmin and pass your required no.of array. it will create multidimenssion array
print(n)
print(n.ndim)

[[[[[[[[[[1 2 3 4 5]]]]]]]]]]
10


# Zeros Array Element

In [37]:
n = np.zeros(4) #print 4 element array
m = np.zeros((,4))#print 3 x 4 array

print(n)
print()
print(m)

[0. 0. 0. 0.]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


# Ones Array

In [28]:
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [40]:
data = np.ones_like(m)
data


array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# Empty Array

In [29]:
ar_em = np.empty(4)
print(ar_em)

[0. 0. 0. 0.]


# Digonal 

In [31]:
ar_dia = np.eye((3))
print(ar_dia)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# linspace

In [36]:
ar_lin = np.linspace(0,10 ,num =9) #it will create equal number of space betwwen the number
print(ar_lin)

[ 0.    1.25  2.5   3.75  5.    6.25  7.5   8.75 10.  ]


In [37]:
ar_lin = np.linspace(0,50 ,num =5) #it will create equal number of space betwwen the number
print(ar_lin)

[ 0.  12.5 25.  37.5 50. ]


# Random Number Array

## Rand() it will create an array between 0 and 1

In [4]:
var = np.random.rand(4)
print(var)

[0.04010165 0.4901851  0.48292363 0.17420977]


In [6]:
var1 = np.random.rand(3,6) #it will create 3 x 6(3 rows and 6 columns) array and number between 0 and 1
print(var1)

[[0.28609677 0.69950217 0.21814118 0.14068512 0.64059297 0.59834133]
 [0.69270125 0.43374175 0.71035068 0.67123287 0.0619669  0.41851636]
 [0.86884582 0.826873   0.58898304 0.53848537 0.60902421 0.676657  ]]


# Randn() it will generate a number near to Zero number may be positive or negative

In [7]:
var2 =  np.random.randn(5)
print(var2)

[ 0.71650116  0.79203643 -1.66591025  0.2572156   1.32643648]


## Ranf() it will generate an array may be start from zero but always less than 0ne.one is not include like [ o.o,   1)

In [10]:
var3 = np.random.ranf(5) #in above heading square bracket shows that array start from 0 and circle bracket shows that one is not include.
print(var3)

[0.59029527 0.20440395 0.51834029 0.38944399 0.60794368]


## Randint() it will generate an array of random number we decleare a range

In [12]:
var4 = np.random.randint( 5, 20 ,8) # randint(min value, max value , total number of values to generate)
print(var4)

[17 19 19 13 14  9 13 15]


# Data Type in numpy

In [14]:
v1 = np.array([1,2,3,4,5,67])

print("Data Type : " , v1.dtype)

Data Type :  int32


In [17]:
v2 = np.array([1.1,2,3.2,4.2,5.22,67.2])

print("Data Type : " , v2.dtype)

Data Type :  float64


In [18]:
v3 = np.array([1.1,2,3.2,4.2,5.22,67.2])

print("Data Type : " , v3.dtype)

Data Type :  float64


In [19]:
v4 = np.array(["a","S",1.1,2,3.2,4.2,5.22,67.2])

print("Data Type : " , v4.dtype)

Data Type :  <U32


# Convert any data type then use np.any_type

In [20]:
b = np.array([1,2,3,4], dtype = np.int8)
print("Data Type : " , b.dtype)

Data Type :  int8


In [21]:
b1 = np.array([1,2,3,4], dtype = "f") # f stand for float
print("Data Type : " , b1.dtype)
print(b1)

Data Type :  float32
[1. 2. 3. 4.]


In [22]:
b1 = np.array([1,2,3,4])

new = np.float32(b1)

print("Data Type : " , b1.dtype)

print(b1)

print("Data Type : " , new.dtype)

print(new)

Data Type :  int32
[1 2 3 4]
Data Type :  float32
[1. 2. 3. 4.]


In [24]:
b1 = np.array([1,2,3,4])

new = np.float32(b1)

new_1 = np.int_(new)

print("Data Type : " , b1.dtype)

print(b1)

print("Data Type : " , new.dtype)

print(new)

print("Data Type : " , new_1.dtype)

print(new_1)

Data Type :  int32
[1 2 3 4]
Data Type :  float32
[1. 2. 3. 4.]
Data Type :  int32
[1 2 3 4]


In [25]:
b2 = np.array([1,2,3,4])

new_2 = b2.astype(float) #astype convert b1 data type int into float


print(b2)
print("Data Type : " , b2.dtype)
print()
print(new_2)

print("Data Type : " , new_2.dtype)

[1 2 3 4]
Data Type :  int32

[1. 2. 3. 4.]
Data Type :  float64


# Arithmatic Opperation

# 1D Array

In [3]:
num1 = np.array([1,2,3,4])
num_add = num1+5
print(num_add)    

[6 7 8 9]


In [5]:
data = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
data + 5

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [28]:
num1 = np.array([1,2,3,4])
num2 = np.array([3,4,5,6])
num_add = num1+num2
print(num_add)

[ 4  6  8 10]


In [29]:
num1 = np.array([1,2,3,4])
num_add = num1-5
print(num_add) 

[-4 -3 -2 -1]


In [6]:
data = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
data - 5

array([[-4, -3, -2],
       [-1,  0,  1],
       [ 2,  3,  4]])

In [30]:
num1 = np.array([1,2,3,4])
num_add = num1*5
print(num_add) 

[ 5 10 15 20]


In [7]:
data = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
data * 5

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [31]:
num1 = np.array([1,2,3,4])
num_add = num1/5
print(num_add) 

[0.2 0.4 0.6 0.8]


In [8]:
data = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
data / 5

array([[0.2, 0.4, 0.6],
       [0.8, 1. , 1.2],
       [1.4, 1.6, 1.8]])

In [33]:
num1 = np.array([1,2,3,4])
num_add = num1%3
print(num_add) 

[1 2 0 1]


In [9]:
data = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
data % 5

array([[1, 2, 3],
       [4, 0, 1],
       [2, 3, 4]], dtype=int32)

In [34]:
num1 = np.array([1,2,3,4])
num2 = np.array([3,4,5,6])
num_add =np.add(num1,num2)
print(num_add)

[ 4  6  8 10]


In [35]:
num1 = np.array([1,2,3,4])
num2 = np.array([3,4,5,6])
num_add =np.add(num1,5)
print(num_add)

[6 7 8 9]


# 2D Array

In [43]:
n1 = np.array([[1,2,3,4],[1,2,3,4]])
n2 = np.array([[2,3,4,5],[3,4,5,6]])

print(n1)
print()
print(n2)
n3 = np.add(n1,n2)
print()
print(n3)

[[1 2 3 4]
 [1 2 3 4]]

[[2 3 4 5]
 [3 4 5 6]]

[[ 3  5  7  9]
 [ 4  6  8 10]]


# Arithmatic Function

In [45]:
c = np.array([1,1,2,3,4,5,6,7,9,5])
print(np.min(c),np.argmin(c))
print(np.max(c),np.argmax(c)) # np.arg tell us the index number

1 0
9 8


In [54]:
vf = np.array([[2,6,8,5],[4,5,6,7]])
print("min :",np.min(vf,axis = 1)) # axis = 1 deals with row
print("max :",np.max(vf,axis = 1))
print("min :", np.min(vf,axis = 0)) # axis = 0 deals with columns
print("max :",np.max(vf,axis = 0))

min : [2 4]
max : [8 7]
min : [2 5 6 5]
max : [4 6 8 7]


In [56]:
c = np.array([4,9,16,25,36])
print(np.sqrt(c))

[2. 3. 4. 5. 6.]


In [57]:
c = np.array([4,9,16,25,36])
print(np.sin(c))
print(np.cos(c))

[-0.7568025   0.41211849 -0.28790332 -0.13235175 -0.99177885]
[-0.65364362 -0.91113026 -0.95765948  0.99120281 -0.12796369]


In [58]:
c = np.array([1,1,2,3,4,5,6,7,9,5])
print(np.cumsum(c))#add each number in array in previous number

[ 1  2  4  7 11 16 22 29 38 43]


# Shape and Reshapping

In [60]:
var =  np.array([[2,3,4,5],[3,4,5,6]])
print(var)
print(var.shape)

[[2 3 4 5]
 [3 4 5 6]]
(2, 4)


In [66]:
var1 =  np.array([2,3,4,5] , ndmin=4)
print(var1)
print(var1.shape)

[[[[2 3 4 5]]]]
(1, 1, 1, 4)


In [10]:
var2 = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
print(var2)
print(var2.ndim)

print()

x = var2.reshape(2,3,2)
print(x)
print(x.ndim)

print()

one = x.reshape(-1)# convert multidimenssion into one dimenssion
print(one)
print(one.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]
3

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [15]:
data = np.arange(2*3*10*10).reshape(2,3,10,10)
data

array([[[[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9],
         [ 10,  11,  12,  13,  14,  15,  16,  17,  18,  19],
         [ 20,  21,  22,  23,  24,  25,  26,  27,  28,  29],
         [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39],
         [ 40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
         [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59],
         [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69],
         [ 70,  71,  72,  73,  74,  75,  76,  77,  78,  79],
         [ 80,  81,  82,  83,  84,  85,  86,  87,  88,  89],
         [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99]],

        [[100, 101, 102, 103, 104, 105, 106, 107, 108, 109],
         [110, 111, 112, 113, 114, 115, 116, 117, 118, 119],
         [120, 121, 122, 123, 124, 125, 126, 127, 128, 129],
         [130, 131, 132, 133, 134, 135, 136, 137, 138, 139],
         [140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
         [150, 151, 152, 153, 154, 155, 156, 157, 158, 159],
         [160, 161, 16

# Broadcasting

In [80]:
x = np.array([1,2,3,4])
print(x.shape)
print(x)
print()
y = np.array([[1],[2],[3]])
print(y.shape)
print(y)
print()
print(x+y)

(4,)
[1 2 3 4]

(3, 1)
[[1]
 [2]
 [3]]

[[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]


In [85]:
x1 = np.array([[1],[2]])
print(x1.shape)
print(x1)
print()

x2 = np.array([[1,3,4],[3,4,4]])
print(x2.shape)
print(x2)
print()

print(x1+x2)

(2, 1)
[[1]
 [2]]

(2, 3)
[[1 3 4]
 [3 4 4]]

[[2 4 5]
 [5 6 6]]


# Indexing

In [5]:
var3 = np.array([1,2,3,4])
print(var3)
print(var3.ndim)  #ndim tell us the dimenssion of array
print(var3[3])

[1 2 3 4]
1
4


In [28]:
var4 = np.array([[1,2,3,4],[4,5,6,7],[2,3,4,5]])
print(var4)
print(var4.ndim)
print(var4[0,2])
print(var4[1,3])
print(var4[2,3])

[[1 2 3 4]
 [4 5 6 7]
 [2 3 4 5]]
2
3
7
5


In [19]:
var5 = np.array([[[4,5,6,7],[6,4,2,4],[3,4,5,6]]])
print(var5)
print(var5.ndim)
print(var5[0,1,2])
print(var5[0,2,2])

[[[4 5 6 7]
  [6 4 2 4]
  [3 4 5 6]]]
3
2
5


In [21]:
var5 = np.array([[[4,5,6,7],[6,4,2,4],[3,4,5,6],[3,5,6,7]]])
print(var5)
print(var5.ndim)
print(var5[0,1,2])
print(var5[0,2,2])
print(var5[0,3,1])

[[[4 5 6 7]
  [6 4 2 4]
  [3 4 5 6]
  [3 5 6 7]]]
3
2
5
5


# Slicing

In [27]:
var6 = np.array([1,2,3,4,5,6,7,8,9])
print(" 2 to 7 : " ,var6[2:7])
print(" Start to 7 : ", var6[:7])
print(" Start to end with Step 2 :" , var6[: : 2])
print(" 2 to end : ", var6[2 :])

 2 to 7 :  [3 4 5 6 7]
 Start to 7 :  [1 2 3 4 5 6 7]
 Start to end with Step 2 : [1 3 5 7 9]
 2 to end :  [3 4 5 6 7 8 9]


In [30]:
var6 = np.array([[3,4,5,6],[6,4,3,2]])
print(var6[1,1:4])

[4 3 2]


In [31]:
var6 = np.array([[[1,2,3,4],[4,5,6,7],[6,3,3,2]]])
print(var6[0,1,1:4])

[5 6 7]


In [23]:
data = np.array([[1,2,3,4],
                [4,5,6,7],
               [3,4,6,7]])
print(data[:,2])
print(data[:,0])

[3 6 6]
[1 4 3]


In [29]:
data = np.arange(10*10).reshape(10,10)
print(data)
print()
print(data[5:,5:])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

[[55 56 57 58 59]
 [65 66 67 68 69]
 [75 76 77 78 79]
 [85 86 87 88 89]
 [95 96 97 98 99]]


In [30]:
data = np.arange(10*10).reshape(10,10)
print(data)
print()
print(data[2:-2,2:-2])

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]
 [30 31 32 33 34 35 36 37 38 39]
 [40 41 42 43 44 45 46 47 48 49]
 [50 51 52 53 54 55 56 57 58 59]
 [60 61 62 63 64 65 66 67 68 69]
 [70 71 72 73 74 75 76 77 78 79]
 [80 81 82 83 84 85 86 87 88 89]
 [90 91 92 93 94 95 96 97 98 99]]

[[22 23 24 25 26 27]
 [32 33 34 35 36 37]
 [42 43 44 45 46 47]
 [52 53 54 55 56 57]
 [62 63 64 65 66 67]
 [72 73 74 75 76 77]]


# Fancy Slicing

In [3]:
a = np.array([2,3,4,6,7,9,5])
a[[3,6]] # pass any index it will return

array([6, 5])

In [4]:
a = np.array([2,3,4,6,7,9,5])
a[[-3,2]] # pass any index it will return

array([7, 4])

In [5]:
a = np.array([2,3,4,6,7,9,5])
a[[-3,2,2,3,4,5,6]] # pass any index it will return  if pass same index many time it will return all the time

array([7, 4, 4, 6, 7, 9, 5])

# Iteration in Array

In [40]:
num = np.array([1,2,3,4,5,6,7,8,9])
print(num)
print(num.ndim)
print()

for i in np.nditer(num):
    print(i)

[1 2 3 4 5 6 7 8 9]
1

1
2
3
4
5
6
7
8
9


In [42]:
num = np.array([[1,2,3,4,5,6,7,8,9],[5,4,6,7,4,2,21,34,4]])
print(num)
print(num.ndim)
print()

for i in np.nditer(num):# np.nditer iterate the array
    print(i)

[[ 1  2  3  4  5  6  7  8  9]
 [ 5  4  6  7  4  2 21 34  4]]
2

1
2
3
4
5
6
7
8
9
5
4
6
7
4
2
21
34
4


In [46]:
num = np.array([[1,2,3,4,5,6,7,8,9],[5,4,6,7,4,2,21,34,4]])
print(num)
print(num.ndim)
print()

for i, d in np.ndenumerate(num):# np.ndenumerate iterate the array and also give index number
    print(i)

[[ 1  2  3  4  5  6  7  8  9]
 [ 5  4  6  7  4  2 21 34  4]]
2

(0, 0)
(0, 1)
(0, 2)
(0, 3)
(0, 4)
(0, 5)
(0, 6)
(0, 7)
(0, 8)
(1, 0)
(1, 1)
(1, 2)
(1, 3)
(1, 4)
(1, 5)
(1, 6)
(1, 7)
(1, 8)


# Copy and View

In [47]:
var1 = np.array([1,2,3,4,5])
print(var1)

co= var1.copy()# print orignal array
print(co)

[1 2 3 4 5]
[1 2 3 4 5]


In [49]:
var1 = np.array([1,2,3,4,5])
print(var1)
print()
co= var1.copy()# print orignal array
var1[1]= 40 # if we change an array then print co it cannot change their array
print(var1)
print(co)

[1 2 3 4 5]

[ 1 40  3  4  5]
[1 2 3 4 5]


In [50]:
var1 = np.array([1,2,3,4,5])
print(var1)

vi= var1.view()# print orignal array
print(vi)

[1 2 3 4 5]
[1 2 3 4 5]


In [51]:
var1 = np.array([1,2,3,4,5])
print(var1)
print()
vi= var1.view()# print orignal array
var1[1]= 40 # if we change an array then print vi it will change their array and print a new array
print(var1)
print(vi)

[1 2 3 4 5]

[ 1 40  3  4  5]
[ 1 40  3  4  5]


# Size

In [17]:
data =  np.array([[1,2,3,4],
                 [4,5,3,5],
                 [3,4,56,6]])
print(data.size)

12


# Sorting

In [42]:
d = np.array([23,4,578,53,68,78,4,36,89,6])
print(d)

[ 23   4 578  53  68  78   4  36  89   6]


In [43]:
np.sort(d)

array([  4,   4,   6,  23,  36,  53,  68,  78,  89, 578])

In [45]:
np.argsort(d) # sort according to smallest index

#np.argsort  print index number from smaller to bigger

array([1, 6, 9, 0, 7, 3, 4, 5, 8, 2], dtype=int64)

# Concetenation

# Join Array

In [53]:
f = np.array([2,3,4,56,6])
g = np.array([4,5,3,21,1])
print(np.concatenate([f,g]))



[ 2  3  4 56  6  4  5  3 21  1]


In [51]:
f = np.array([2,3,4,56,6])
g = np.array([4,5,3,21,1])
print(np.vstack([f,g])) # vertical join

[[ 2  3  4 56  6]
 [ 4  5  3 21  1]]


In [52]:
f = np.array([2,3,4,56,6])
g = np.array([4,5,3,21,1])
print(np.hstack([f,g])) # horizontal join

[ 2  3  4 56  6  4  5  3 21  1]


In [54]:
f = np.array([2,3,4,56,6])
g = np.array([4,5,3,21,1])
np.stack([f,g],axis = 0) #axis=0 merge column

array([[ 2,  3,  4, 56,  6],
       [ 4,  5,  3, 21,  1]])

In [3]:
f = np.array([2,3,4,56,6])
g = np.array([4,5,3,21,1])
np.stack([f,g],axis = 1) #axis =1 merge rows

array([[ 2,  4],
       [ 3,  5],
       [ 4,  3],
       [56, 21],
       [ 6,  1]])

# Split Array

In [7]:
data = np.array([1,2,3,4,5,6,7,8,0])
print(data)
ar = np.array_split(data,3)
print(ar)

[1 2 3 4 5 6 7 8 0]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 0])]


In [8]:
data = np.array([[1,2,3,4],[5,6,7,8],[2,5,6,7]])
print(data)
ar = np.array_split(data,3)
print(ar)

[[1 2 3 4]
 [5 6 7 8]
 [2 5 6 7]]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]]), array([[2, 5, 6, 7]])]


# Search

In [10]:
a = np.array([1,2,3,4,5,6,78,54,32,2])
b= np.where(a==2) # where search the value and return its index
print(b)

(array([1, 9], dtype=int64),)


In [15]:
d =  np.array([1,2,4,3,4,7,8,9,8,9])
np.searchsorted(d,5) # np.searchsorted tell the value index in where it will placed
                     # it will count index from left to right   

5

In [19]:
d =  np.array([1,2,3,4,7,8,9,7,4,9])
np.searchsorted(d, 5 , side = "right")

4

In [20]:
d =  np.array([1,2,34,5,6,7,8,9])
np.searchsorted(d, [4,5,6] , side = "right")


array([2, 4, 5], dtype=int64)

In [21]:
d = np.array([3,4,6,7,2,4,6,7])
np.sort(d)

array([2, 3, 4, 4, 6, 6, 7, 7])

In [23]:
data = np.array([[1,4,2,3],[6,5,8,7],[2,65,6,7]])
np.sort(data)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 2,  6,  7, 65]])

# Filter Array

In [25]:
d= np.array(["a","d","f","g"])
e = [True,False,True,False]
m = d[e]
print(m)

['a' 'f']


# np.in1d

In [56]:
bank_cnic = np.arange(1,11)
bank_cnic

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
state_bank = np.array([2,22,3,44,3,9,56,77,78])
state_bank

array([ 2, 22,  3, 44,  3,  9, 56, 77, 78])

In [58]:
np.in1d(state_bank,bank_cnic)

array([ True, False,  True, False,  True,  True, False, False, False])

In [59]:
state_bank[np.in1d(state_bank,bank_cnic)]

array([2, 3, 3, 9])

In [60]:
np.intersect1d(state_bank,bank_cnic)

array([2, 3, 9])

In [26]:
a= np.array([chr(i) for i in range(65,91)],dtype = str)
print(a)

['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R'
 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z']


In [27]:
bank_data = a
print(a)

['A' 'B' 'C' 'D' 'E' 'F' 'G' 'H' 'I' 'J' 'K' 'L' 'M' 'N' 'O' 'P' 'Q' 'R'
 'S' 'T' 'U' 'V' 'W' 'X' 'Y' 'Z']


In [31]:
state_bank = np.array(['A',"G",'a','f','G',"J"])


In [32]:
np.in1d(state_bank,bank_data)

array([ True,  True, False, False,  True,  True])

In [33]:
np.intersect1d(state_bank,bank_data)

array(['A', 'G', 'J'], dtype='<U1')

In [52]:
state_bank = np.array(list(map(str.lower , state_bank)))
print(state_bank)

['a' 'g' 'a' 'f' 'g' 'j']


In [38]:
bank_data = np.array(list(map(str.lower , bank_data)))

In [40]:
np.in1d(state_bank,bank_data)

array([ True,  True,  True,  True,  True,  True])

In [39]:
np.intersect1d(state_bank,bank_data)

array(['a', 'f', 'g', 'j'], dtype='<U1')

# Handel Issue like space,upper and lower letter

In [47]:
def pre_processing(txt):
    txt = str(txt)
    txt = txt.lower()
    txt = txt.strip() # sttrip remove space from start and end of the line
    return txt
pre_processing("     PakisTan Zinda BAd    ")

'pakistan zinda bad'

In [50]:
import re
def pre_processing(txt):
    txt = str(txt)
    txt = txt.lower()
    txt = txt.strip() # sttrip remove space from start and end of the line
    txt = re.sub("(2,100)"," " ,txt) # remove space 2 0r 100 with in a txt it will remove
    return txt
pre_processing("     PakisTan Zinda BAd    ")

'pakistan zinda bad'

In [53]:
state_bank = np.array(list(map(pre_processing , state_bank)))
print(state_bank)

['a' 'g' 'a' 'f' 'g' 'j']
